export const WhatsappPhoneNumber = +254757011738;

export const SPEC_CATEGORIES = {
  "General Information": ["price", "brand", "category", "stock", "rating"],
  "Technical Specifications": [
    "processor",
    "cpu",
    "ram",
    "memory",
    "storage",
    "ssd",
    "hdd",
    "graphics",
    "gpu",
    "display",
    "screen",
    "screensize",
    "screen size",
    "resolution",
    "os",
    "operating_system",
    "battery",
    "camera",
    "connectivity",
    "wifi",
    "bluetooth",
  ],
  "Physical Specifications": [
    "weight",
    "dimensions",
    "size",
    "color",
    "material",
    "design",
  ],
  Features: [
    "features",
    "ports",
    "optical_drive",
    "touchscreen",
    "backlit_keyboard",
    "fingerprint",
    "webcam",
  ],
};
